services:
  lemmy-ui:
    image: dockurr/lemmy-ui
    container_name: lemmy-ui
    environment:
      - LEMMY_UI_HTTPS=true
      - LEMMY_UI_LEMMY_INTERNAL_HOST=lemmy:8536
      - LEMMY_UI_LEMMY_EXTERNAL_HOST=domain.tld
    ports:
      - 1234:1234
    restart: always
    stop_grace_period: 1m
